// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto

// Protobuf Java Version: 4.26.1
package com.hrishi.api.grpc;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hrishi.api.grpc.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1;</code>
   * @return The greeting.
   */
  java.lang.String getGreeting();
  /**
   * <code>string greeting = 1;</code>
   * @return The bytes for greeting.
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
